name: example
version: 1.0.0
private: true

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^5.1.1
  build_runner: ^2.4.15
  font_awesome_pro_flutter:
    path: ..
