import 'icon_reference.dart';
import 'style.dart';

const _lineLength = 80;

/// Renders the generated library for [style].
///
/// Emitted as text rather than through `code_builder` + `dart_style` so the
/// package carries no dependency that itself depends on `analyzer`. The
/// output is already formatted the way `dart format` would leave it.
String emitLibrary(FontAwesomeStyle style, Iterable<IconReference> icons) {
  final sorted = icons.toList()..sort();
  final buffer = StringBuffer()
    ..writeln('// GENERATED CODE - DO NOT MODIFY BY HAND')
    ..writeln('// Generated by package:font_awesome_pro_flutter.')
    // A style with no referenced icons still gets a library, so that the
    // build output is the same set of files every time.
    ..writeln('// ignore_for_file: unused_import, unused_field')
    ..writeln()
    ..writeln("import 'package:flutter/widgets.dart';")
    ..writeln()
    ..writeln('class ${style.className} {')
    ..writeln('  ${style.className}._();')
    ..writeln();

  for (final icon in sorted) {
    buffer
      ..writeln(_field(icon))
      ..writeln();
  }

  return (buffer
        ..writeln("  static const _fontFamily = '${style.fontFamily}';")
        ..writeln('}'))
      .toString();
}

String _field(IconReference icon) {
  final declaration = '  static const IconData ${icon.fieldName} =';
  final value = 'IconData(${icon.codePoint}, fontFamily: _fontFamily);';

  final oneLine = '$declaration $value';
  if (oneLine.length <= _lineLength) return oneLine;

  return '$declaration\n'
      '      IconData(${icon.codePoint}, fontFamily: _fontFamily);';
}
