// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by package:font_awesome_pro_flutter.
// ignore_for_file: unused_import, unused_field

import 'package:flutter/widgets.dart';

class FABrands {
  FABrands._();

  static const _fontFamily = 'FontAwesomeBrands';
}
