// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by package:font_awesome_pro_flutter.
// ignore_for_file: unused_import, unused_field

import 'package:flutter/widgets.dart';

class FARegular {
  FARegular._();

  static const IconData faMinus = IconData(61544, fontFamily: _fontFamily);

  static const _fontFamily = 'FontAwesomeRegular';
}
